import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { DialogProvider } from "../components/Dialog";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ChatDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <main className="bg-gray-950 h-screen">
          <DialogProvider>
            {children}
          </DialogProvider>
        </main>
      </body>
    </html>

  );
}
